### ISSUE TITLE
create new LIZARD archive give me error - wrong parameter

### ISSUE THREAD

**Issue by FadeMind** [Wilenty/7-Zip-X64-X86-with-Extracting-NSIS-script#3] opened 2022-06-28 15:23 UTC
Select 
![20220628-1656429791](https://user-images.githubusercontent.com/9846948/176217990-a924d966-a83a-4497-838b-9557b8728e54.png)
Error after click on OK
![20220628-1656429715](https://user-images.githubusercontent.com/9846948/176218059-de6784ac-ab0a-4d28-88f3-5de860e93ea0.png)

**Comment by Wilenty** [comment] 2022-06-28 15:31
Hello,
can you change the language in 7-zip to English and post the screenshot of 7-zip LIZARD configuration?

You know, I am not the owner/creator of the Codecs, but I can look at it if I will know what you doing there.

**Comment by FadeMind** [comment] 2022-06-28 15:36
Hi,
prompt in translator give:
`Parameter is invalid`
Wizard archive creation window have default setup. 

![20220628-1656430599](https://user-images.githubusercontent.com/9846948/176221101-4845f467-92e6-4f17-bdd7-f3b04be7f497.png)

**Comment by Wilenty** [comment] 2022-06-28 15:51
Okay,
I will investigate it and I will let you know later.

**Comment by Wilenty** [comment] 2022-06-28 17:18
At the outset, because I don't like to wait for the answer forever, I also trying to answer as fast as possible when "I am on board".

I checked the problem with creating LIZARD archives, I even checked the versions of 7-zip back to the 21.03, but none of them can create LIZARD (*.liz) archives via GUI, even if all versions of 7-zip opens them correctly. But, any of them creates *.liz archives via command-line correctly. I don't know where the problem is, as I said, I am not the owner/creator of the DLL to support the Codecs.

![CreatigLIZARDfromCommand-line](https://user-images.githubusercontent.com/61757638/176239462-6c869e44-3a87-4b7b-bc53-127e9ebb3b2b.png)

So, there are few solutions to solve the problem with creating LIZARD (*.liz) archives:

1) create them from command-line, eventually, via batch script (attached example 7z.cmd in 7z.zip):
[7z.zip](https://github.com/Wilenty/7-Zip-X64-X86-with-Extracting-NSIS-script/files/9003335/7z.zip)

2) use mixed installation of standard 7-zip (without Codecs) with NanaZip.dll via 7zTC:
https://github.com/Wilenty/7zTC-7-ZIP-NanaZip-Theme-Changer
you can install 7-zip + NanaZip.dll and apply all themes or none of them at the same execution. You will have the access to all archives formats in 7-zip which NanaZip supports.
![7-ZIP+NanaZipDLL](https://user-images.githubusercontent.com/61757638/176241495-6934fbb6-7a07-4fca-a9a7-cb3722d78417.png)

3) use 7zTC to install NanaZip as standard app, it will add the shell extensions and adds uninstall section entry in the OS registry. And also you can change all of the themes, or none of them at the same execution as in the above.
![NanaZip](https://user-images.githubusercontent.com/61757638/176241900-3f21fa15-df09-4173-87b7-3ef1f3f84da5.png)

If you have any questions, or suggestions - please let me know.
And please close this issue, if my answer solved the problem.

Greetings,
Wilenty

**Closed as completed** 2022-06-28 20:19 UTC
Labels: codecs-bug
